ALTER SESSION SET CURRENT_SCHEMA =dkingston;

DESC POBYRNE.PAINTER;

CREATE TABLE ARTIST(	
  PAINTER_ID CHAR(6) NOT NULL,
	PAINTER_NAME VARCHAR2(50) NOT NULL,
	PAINTER_GENRE VARCHAR2(20),
  PAINTER_DOB DATE
  );
  
  DROP TABLE ARTIST;
  
  INSERT INTO ARTIST SELECT * FROM POBYRNE.PAINTER;
  
  SELECT * FROM ARTIST;
  
  ALTER TABLE ARTIST ADD ARTIST_AGE NUMBER(100);

  
  CREATE TABLE PAINTING(
    CATALOGUE_NUMBER NUMBER(6) PRIMARY KEY,
    TITLE VARCHAR2(50) NOT NULL,
    YEAR_PAINTED DATE NOT NULL,
    ARTIST_ID NUMBER(50)
    );
    
Insert into PAINTING (CATALOGUE_NUMBER,TITLE,YEAR PAINTED,ARTIST_ID) values (300,'Mona Lisa','16/MAR/15','127');
Insert into PAINTING (CATALOGUE_NUMBER,TITLE,YEAR PAINTED,ARTIST_ID) values (301,'Mona Lisa','16/MAR/15','127');
Insert into PAINTING (CATALOGUE_NUMBER,TITLE,YEAR PAINTED,ARTIST_ID) values (302,'Mona Lisa','16/MAR/15','127');
Insert into PAINTING (CATALOGUE_NUMBER,TITLE,YEAR PAINTED,ARTIST_ID) values (303,'Mona Lisa','16/MAR/15','127');

SELECT * FROM PAINTING;

DROP TABLE PAINTING;